# version: '3.8' syntax version

volumes:
  postgres_volume_local:
  postgres_volume_prod:
  prometheus_data:
  grafana_data:

services: # перечисление используемых сервисов
  postgres-local: # название сервиса и ниже его описание
    image: postgres:15-alpine3.17
    restart: no
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  postgres-prod: # название сервиса и ниже его описание
    image: postgres:15-alpine3.17
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    ports:
      - "54322:5432"
    volumes:
      - postgres_volume_prod:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./configs/prometheus/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana