server:
  host: "localhost"
  port: 50051
log:
  level: "debug"

#database:
#  host: "localhost"
#  port: 5432
#  user: "dbuser"
#  password: "dbpass"
#  dbname: "mydb"
#  sslmode: "disable"  # или "require"
#  max_open_conns: 10
#  max_idle_conns: 5
#  conn_max_lifetime: 300s
