server:
  host: "localhost"
  port: 50051
log:
  level: "debug"
database:
  host: "localhost"
  port: "54321"  # Используем из .env
  user: "auth_user"
  password: "auth_password"
  dbname: "auth_db"
  sslmode: "disable"