server:
  host: "localhost"
  port: 50052
log:
  level: "info"
database:
  host: "localhost"
  port: "54322"  # Используем из .env
  user: "auth_user"
  password: "auth_password"
  dbname: "auth_db"
  sslmode: "disable"
